### ISSUE TITLE
Can you specific some parameters in the interface?

### ISSUE THREAD

**Issue by vigosser** [xuqiongkai/ALTER#1]
Can you specify some numbers in the interface?Like  ppl, wmd, ed..
![image](https://user-images.githubusercontent.com/9714310/68914056-37c06300-0798-11ea-8ad0-b25bc5d861e5.png)

**Comment by xuqiongkai** [comment]
They are sentence evaluation scores which are mainly used for measuring the quality of the sentence generated by users/annotators.
For more details, please check our paper at https://www.aclweb.org/anthology/D19-3003.pdf
